CREATE DATABASE QLDP
GO

SET DATEFORMAT DMY
USE QLDP


DROP TABLE PHIEUNHAP
DROP TABLE CTPN
DROP TABLE DUOCPHAM
DROP TABLE NHACUNGCAP

--Tao bang NHACUNGCAP --
CREATE TABLE NHACUNGCAP
(
	MANCC CHAR(5) PRIMARY KEY, 
	TENNCC VARCHAR(40),
	QUOCGIA VARCHAR(40),
	LOAINCC VARCHAR(40)
);
GO

--TAO BANG DUOCPHAM
CREATE TABLE DUOCPHAM
(
	MADP CHAR(4) PRIMARY KEY, 
	TENDP VARCHAR(40),
	LOAIDP VARCHAR(40),
	GIA MONEY NOT NULL
);
GO

--TAO BANG PHIEUNHAP
CREATE TABLE PHIEUNHAP
(
	SOPN CHAR(5) PRIMARY KEY, 
	NGNHAP SMALLDATETIME,
	MANCC CHAR(5) FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	LOAINHAP VARCHAR(40)
);
GO

--TAO BANG CTPN
CREATE TABLE CTPN
(
	SOPN CHAR(5) FOREIGN KEY REFERENCES PHIEUNHAP(SOPN), 
	MADP CHAR(4) FOREIGN KEY REFERENCES DUOCPHAM(MADP),
	SOLUONG INT,
	PRIMARY KEY (SOPN,MADP)
);
GO

INSERT INTO NHACUNGCAP(MANCC,TENNCC,QUOCGIA,LOAINCC) 
VALUES ('NCC01','Phuc Hung','Viet Nam','Thuong xuyen'), 
	('NCC02','J. B. Pharmaceuticals','India','Vang lai'),
	('NCC03','Sapharco','Singapore','Vang lai')

SELECT *
FROM NHACUNGCAP

INSERT INTO DUOCPHAM(MADP,TENDP,LOAIDP,GIA) 
VALUES ('DP01','Thuoc ho PH','Siro','120000'), 
	('DP02','Zecuf Herbal CouchRemedy','Vien nen','200000'), 
	('DP03','Cotrim','Vien nen','80000')

SELECT *
FROM DUOCPHAM

INSERT INTO PHIEUNHAP(SOPN,NGNHAP,MANCC,LOAINHAP) 
VALUES ('00001','22/11/2017','NCC01','Noi dia'),
		('00002','04/12/2017','NCC03','Nhap khau'),
		('00003','10/12/2017','NCC02','Nhap khau')

SELECT *
FROM PHIEUNHAP

INSERT INTO CTPN(SOPN,MADP,SOLUONG) 
VALUES ('00001','DP01',100),
		('00001','DP02',200),
		('00003','DP03',543)

SELECT *
FROM CTPN

-- Rang buoc toan ven cau 3
ALTER TABLE DUOCPHAM
ADD CONSTRAINT CHK_GIASIRO CHECK (LOAIDP != 'Siro' OR GIA > 100000)
GO

-- C4: Hiện thực ràng buộc toàn vẹn sau: Phiếu nhập của những nhà cung cấp ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu
CREATE OR ALTER TRG_phieunhapcheck 
ON PHIEUNHAP 
AFTER INSERT, UPDATE
AS
BEGIN
	DECLARE @MANCC CHAR(5), @LOAINHAP VARCHAR(40), @QUOCGIA VARCHAR(40),
	SELECT @MANCC = MANCC, @LOAINHAP = LOAINHAP 
	FROM INSERTED
	SELECT @QUOCGIA = QUOCGIA 
	FROM NHACUNGCAP 
	WHERE MANCC = @MANCC
	IF ( @QUOCGIA != 'Viet Nam' AND @LOAINHAP = 'Nhap khau')
	 BEGIN
		PRINT 'Them moi phieu nhap thanh cong'
	END
	ELSE 
	BEGIN
		PRINT 'Loi: Phiếu nhập của những nhà cung cấp ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu'
		ROLLBACK TRANSACTION
	 END
END

-- C5: 
SELECT *
FROM PHIEUNHAP
WHERE MONTH(NGNHAP) = '12' AND YEAR(NGNHAP) = '2017'
ORDER BY NGNHAP ASC
GO

-- C6: nHAP SO LUONG NHIEU NHAT 2017
SELECT TOP 1 WITH TIES DUOCPHAM.MADP, SUM(CTPN.SOLUONG) AS TOTAL_SOLUONG
FROM DUOCPHAM
JOIN CTPN ON CTPN.MADP = DUOCPHAM.MADP
JOIN PHIEUNHAP ON CTPN.SOPN = PHIEUNHAP.SOPN
WHERE YEAR(PHIEUNHAP.NGNHAP) = '2017'
GROUP BY DUOCPHAM.MADP
ORDER BY TOTAL_SOLUONG DESC;

-- C7: TÌM DƯỢC PHẨM CHỈ CÓ NHÀ CUNG CẤP THƯỜNG XUYÊN CUNG CẤP, NHÀ CUNG CẤP VÃNG LAI KHÔNG CUNG CẤP
SELECT DUOCPHAM.*
FROM DUOCPHAM
INNER JOIN CTPN CT ON CT.MADP = DUOCPHAM.MADP
INNER JOIN PHIEUNHAP PN ON PN.SOPN = CT.SOPN
WHERE CT.SOPN IN 
(
	SELECT SOPN
	FROM PHIEUNHAP
	INNER JOIN NHACUNGCAP NCC ON NCC.MANCC = PHIEUNHAP.MANCC
	WHERE LOAINCC = 'Thuong xuyen'
	EXCEPT
	SELECT SOPN
	FROM PHIEUNHAP
	INNER JOIN NHACUNGCAP NCC ON NCC.MANCC = PHIEUNHAP.MANCC
	WHERE LOAINCC = 'Vang lai'
)

-- C8: TIM NHA CUNG CAP DA TUNG CUNG CAP TAT CA NHUNG LOAI DUOC PHAM CO GIA TREN 100000 TRONG NAM 2017
SELECT *
FROM NHACUNGCAP NCC
WHERE NOT EXISTS
(
	SELECT *
	FROM DUOCPHAM
	WHERE GIA > 100000 AND NOT EXISTS (
		SELECT *
		FROM CTPN CT
		INNER JOIN PHIEUNHAP PN ON PN.SOPN = CT.SOPN
		WHERE NCC.MANCC = PN.MANCC AND CT.MADP = DUOCPHAM.MADP AND YEAR(NGNHAP) = '2017'
	)
)