CREATE DATABASE THITHU1
GO

SET DATEFORMAT DMY
USE THITHU1

--Tao bang SACH --
CREATE TABLE SACH
(
	MaSach CHAR(5) PRIMARY KEY, 
	TenSach NVARCHAR(100),
	TheLoai NVARCHAR(30),
	DonGia money,
	SoLuong int
);
GO

--TAO BANG TACGIA
CREATE TABLE TACGIA
(
	MaTG CHAR(5) PRIMARY KEY, 
	HoTen NVARCHAR(50),
	QuocTich NVARCHAR(30),
	NgaySinh smalldatetime,
	DienThoai varchar(15)
);
GO

--TAO BANG TACGIA_SACH
CREATE TABLE TACGIA_SACH
(
	MaTG CHAR(5) FOREIGN KEY REFERENCES TACGIA(MaTG), 
	MaSach CHAR(5) FOREIGN KEY REFERENCES SACH(MaSach),
	PRIMARY KEY (MaTG,MaSach)
);
GO

--TAO BANG DOCGIA
CREATE TABLE DOCGIA
(
	MaDG CHAR(5) PRIMARY KEY, 
	TenDG NVARCHAR(50),
	DiaChi NVARCHAR(50),
	NgaySinh smalldatetime,
	DienThoai varchar(15),
	NgDK smalldatetime
);
GO

--TAO BANG PHATHANH
CREATE TABLE PHATHANH
(
	MaPH CHAR(5) PRIMARY KEY, 
	MaSach CHAR(5) FOREIGN KEY REFERENCES SACH(MaSach),
	NgayPH smalldatetime,
	SoLuong int,
	NXB Nvarchar(100),
	LanPhatHanh int
);
GO

--TAO BANG MUONSACH
CREATE TABLE MUONSACH
(
	MaMuon CHAR(5) PRIMARY KEY, 
	MaDG CHAR(5) FOREIGN KEY REFERENCES DOCGIA(MaDG),
	MaSach CHAR(5) FOREIGN KEY REFERENCES SACH(MaSach),
	NgayMuon smalldatetime,
	NgayTra smalldatetime,
	TrangThai Nvarchar(20)
);
GO

--C2: trigger
CREATE OR ALTER TRIGGER TRG_C2 ON PHATHANH AFTER INSERT, UPDATE
AS 
BEGIN
	DECLARE @MaSach char(5), @NgayPH smalldatetime, @NgaySinh smalldatetime
	SELECT @MaSach = MaSach, @NgayPH = NgayPH FROM inserted
	SELECT @NgaySinh = NgaySinh FROM TACGIA 
	WHERE MaTG IN 
		(
			SELECT MaTG
			FROM TACGIA_SACH
			WHERE @MaSach = MaSach
		)
	IF(DAY(@NgayPH) > DAY(@NgaySinh))
	BEGIN
		PRINT('THANH CONG')
	END
	ELSE
	BEGIN
		PRINT('THAT BAI')
		ROLLBACK TRAN
	END
END

--C3: 
ALTER TABLE PHATHANH
ADD CONSTRAINT CHK_SL CHECK(SoLuong>500)

--C4:
SELECT DG.*
FROM DOCGIA DG
INNER JOIN MUONSACH MS ON DG.MaDG = MS.MaDG
WHERE NgayMuon = 10/12/2024

--C5:
SELECT TG.MaTG, TG.HoTen
FROM TACGIA TG
INNER JOIN TACGIA_SACH TS ON TS.MaTG = TG.MaTG
INNER JOIN SACH S ON S.MaSach = TS.MaSach
INNER JOIN PHATHANH PH ON PH.MaSach = S.MaSach
WHERE S.TenSach = N'Cấu trúc rời rạc' AND NXB = N'DHQG-HCM'

---C6:
SELECT TG.MaTG, TG.HoTen, SUM(SoLuong) AS TongSoLuongSach
FROM TACGIA TG
INNER JOIN TACGIA_SACH TS ON TS.MaTG = TG.MaTG
INNER JOIN SACH S ON S.MaSach = TS.MaSach
GROUP BY TG.MaTG, TG.HoTen
ORDER BY TongSoLuongSach DESC

SELECT *
FROM MUONSACH

---C7:
SELECT DG.MaDG, DG.TenDG
FROM DOCGIA DG
INNER JOIN MUONSACH MS ON DG.MaDG = MS.MaDG
INNER JOIN SACH S ON S.MaSach = MS.MaSach
WHERE YEAR(MS.NgayMuon) = 2024 
GROUP BY DG.MaDG, DG.TenDG
HAVING COUNT(DISTINCT TheLoai) >= 3

SELECT *
FROM SACH
SELECT *
FROM PHATHANH
SELECT *
FROM MUONSACH

---C8:
SELECT PH.NXB
FROM PHATHANH PH
INNER JOIN SACH S ON S.MaSach = PH.MaSach
WHERE NOT EXISTS
	(
		SELECT *
		FROM MUONSACH
		--WHERE 
	)
GROUP BY PH.NXB
HAVING COUNT(DISTINCT TheLoai) > 5

--C9:
SELECT DG.MaDG, DG.TenDG
FROM DOCGIA DG
WHERE NOT EXISTS
	(
		SELECT *
		FROM SACH SX
		WHERE S.TheLoai IN(N'Khoa học viễn tưỡng', N'Kinh Tế')
		      AND NOT EXISTS
			  (
				SELECT * 
				FROM MUONSACH MS
				WHERE DG.MaDG = MS.MaDG AND MS.MaSach = S.MaSach AND YEAR(MS.NgayMuon) = 2024
			  )
	)

--Cach 2:
SELECT DG.MaDG, DG.TenDG
FROM DOCGIA DG
WHERE NOT EXISTS
	(
		SELECT *
		FROM SACH S
		WHERE EXISTS
			(
			 SELECT TheLoai
			 FROM SACH
			 WHERE TheLoai = N'Khoa học viễn tưởng' 
			 INTERSECT
			 SELECT TheLoai
			 FROM SACH
			 WHERE TheLoai = N'Kinh tế'
			)
		      AND NOT EXISTS
			  (
				SELECT * 
				FROM MUONSACH MS
				WHERE DG.MaDG = MS.MaDG AND MS.MaSach = S.MaSach AND YEAR(MS.NgayMuon) = 2024
			  )
	)

INSERT INTO TACGIA VALUES ('TG001', 'NGUYEN VAN A', 'VIETNAM', '20/11/1999', '0987619467')

INSERT INTO SACH VALUES ('S00L1', 'TRUYEN 18+', 'KINH DI', 100000, 10)

INSERT INTO TACGIA_SACH VALUES ('TG001', 'S00L1')

INSERT INTO PHATHANH VALUES ('PH001', 'S00L1', '20/11/2023', 100, 'KIM DONG', 10)

INSERT INTO DOCGIA VALUES ('DG001', 'MINH MAI', 'TP.HCM', '11/12/2005', '099999999', '21/12/2001')

INSERT INTO MUONSACH VALUES ('MS001', 'DG001', 'S00L1', '10/12/2024', '11/12/2024', 'CHUA TRA')